apiVersion: v1
kind: ConfigMap
metadata:
  name: mx-job-operator-config
  namespace: default
data:
  controller_config_file.yaml: |
    accelerators:
      alpha.kubernetes.io/nvidia-gpu:
        volumes:
          - name: nvidia-libraries
            mountPath: /usr/local/nvidia/lib64 # This path is special; it is expected to be present in `/etc/ld.so.conf` inside the container image.
            hostPath: /home/kubernetes/bin/nvidia/lib
          - name: nvidia-debug-tools # optional
            mountPath: /usr/local/bin/nvidia
            hostPath: /home/kubernetes/bin/nvidia/bin

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mx-job-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mx-job-operator
    spec:
      containers:
      - name: mx-job-operator
        image: {{ .Values.image }}
        command:
          - /opt/mlkube/tf_operator
          - --controller_config_file=/etc/config/controller_config_file.yaml
          - -alsologtostderr
          - -v=1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: mx-job-operator-config
