apiVersion: "mxnet.mlkube.io/v1beta1"
kind: "MxJob"
metadata:
  name: "example-local-job"
spec:
  jobMode: "local"
  replicaSpecs:
    - replicas: 1
      mxReplicaType: WORKER
      template:
        spec:
          containers:
            - image: 10.199.192.16/library/mxnet-gpu-local:0.12.0
              name: mxnet
              command: ["python"]
              args: ["train_cifar10.py","--num-epochs=10","--gpus=0","--model-prefix=./wltest","--num-layers=2"]
              workingDir: "/mxnet/example/image-classification"   
              resources:
                limits:
                  alpha.kubernetes.io/nvidia-gpu: 1                           
          restartPolicy: OnFailure
