apiVersion: "mlkube.io/v1beta1"
kind: "MxJob"
metadata:
  name: "example-dist-job"
spec:
  jobMode: "dist"
  replicaSpecs:
    - replicas: 1
      mxReplicaType: SCHEDULER
      PsRootPort: 9091
      template:
        spec:
          containers:
            - image: 10.199.192.16/tensorflow/wd-mxnet:cuda8.0
              name: mxnet
          restartPolicy: OnFailure
    - replicas: 1
      mxReplicaType: SERVER
      template:
        spec:
          containers:
            - image: 10.199.192.16/tensorflow/wd-mxnet:cuda8.0
              name: mxnet
          restartPolicy: OnFailure
    - replicas: 1
      mxReplicaType: WORKER
      template:
        spec:
          containers:
            - image: 10.199.192.16/tensorflow/wd-mxnet:cuda8.0
              name: mxnet
          restartPolicy: OnFailure          
