apiVersion: "mxnet.mlkube.io/v1beta1"
kind: "MxJob"
metadata:
  name: "example-dist-job"
spec:
  jobMode: "dist"
  replicaSpecs:
    - replicas: 1
      mxReplicaType: SCHEDULER
      PsRootPort: 9091
      template:
        spec:
          containers:
            - image: 10.199.192.16/library/mxnet-gpu-dist:0.12.0
              name: mxnet
              command: ["python"]
              args: ["train_cifar10.py"]
              workingDir: "/mxnet/example/image-classification"
          restartPolicy: OnFailure
    - replicas: 2 
      mxReplicaType: SERVER
      template:
        spec:
          containers:
            - image: 10.199.192.16/library/mxnet-gpu-dist:0.12.0
              name: mxnet
              command: ["python"]
              args: ["train_cifar10.py"]
              workingDir: "/mxnet/example/image-classification"
          restartPolicy: OnFailure
    - replicas: 3
      mxReplicaType: WORKER
      template:
        spec:
          containers:
            - image: 10.199.192.16/library/mxnet-gpu-dist:0.12.0
              name: mxnet
              command: ["python"]
              args: ["train_cifar10.py","--num-epochs=10","--gpus=0","--num-layers=2","--kv-store=dist_device_sync"]
              workingDir: "/mxnet/example/image-classification"
              resources:
                limits:
                  alpha.kubernetes.io/nvidia-gpu: 1              
          restartPolicy: OnFailure
