apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mx-job-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mx-job-operator
    spec:
      containers:
      - name: mx-job-operator
        image: 10.199.192.16/tensorflow/mx_operator:1.7-ca2a96c
        imagePullPolicy: Always
        command:
          - /opt/mlkube/mx_operator
          - -alsologtostderr
          - -v=8
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
