apiVersion: "mlkube.io/v1beta1"
kind: "TfJob"
metadata:
  name: "example-job"
spec:
  replicaSpecs:
    - replicas: 1
      tfReplicaType: MASTER
      template:
        spec:
          containers:
            - image: 10.199.192.16/tensorflow/tf_sample:dc944ff
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 1
      tfReplicaType: WORKER
      template:
        spec:
          containers:
            - image: 10.199.192.16/tensorflow/tf_sample:dc944ff
              name: tensorflow
          restartPolicy: OnFailure
