# This template is used to verify that REPLICAS, psRootPort, and MxReplicaType are properly set to default
# values if unspecified by the user.
apiVersion: "mlkube.io/v1beta1"
kind: "MxJob"
metadata:
  name: "example-job-defaults"
spec:
  replicaSpecs:
    - template:
        spec:
          containers:
            - image: gcr.io/tf-on-k8s-dogfood/tf_sample:dc944ff
              name: tensorflow
          restartPolicy: OnFailure