apiVersion: "mlkube.io/v1beta1"
kind: "MxJob"
metadata:
  name: {{ .Release.Name }}
spec:
  replica_specs:
    - replicas: 1
      PsRootPort: 9091
      mxReplicaType: MASTER
      template:
        spec:
          containers:
            - image: {{ .Values.image }} 
              name: tensorflow
          restartPolicy: OnFailure
    - replicas: 1
      PsRootPort: 9091
      mxReplicaType: WORKER
      template:
        spec:
          containers:
            - image: {{ .Values.image }}
              name: tensorflow
          restartPolicy: OnFailure